import {
  EMAIL_TOO_MANY_REQUEST_ERROR,
  EMAIL_CODE_NOT_MACHTED,
  EMAIL_CODE_EXPIRED,
} from "constants/errorCode";

import {
  EMAIL_DUPLICATED_ERROR_MESSAGE,
  EMAIL_VALIDATION_ERROR_MESSAGE,
  EMAIL_TOO_MANY_REQUEST_ERROR_MESSAGE,
  EMAIL_CODE_MISMATCH_ERROR_MESSAGE,
  EMAIL_CODE_EXPIRED_ERROR_MESSAGE,
  EMAIL_CODE_VALIDATION_ERROR,
} from "constants/errorMessage";

export const emailErrorMap = {
  409: {
    default: EMAIL_DUPLICATED_ERROR_MESSAGE,
  },
  422: {
    default: EMAIL_VALIDATION_ERROR_MESSAGE,
  },
  429: {
    [EMAIL_TOO_MANY_REQUEST_ERROR]: EMAIL_TOO_MANY_REQUEST_ERROR_MESSAGE,
    default: EMAIL_TOO_MANY_REQUEST_ERROR_MESSAGE,
  },
};

export const emailCodeErrorMap = {
  400: {
    [EMAIL_CODE_NOT_MACHTED]: EMAIL_CODE_MISMATCH_ERROR_MESSAGE,
    [EMAIL_CODE_EXPIRED]: EMAIL_CODE_EXPIRED_ERROR_MESSAGE,
    default: EMAIL_CODE_MISMATCH_ERROR_MESSAGE,
  },
  422: {
    default: EMAIL_CODE_VALIDATION_ERROR,
  },
};